"use client";

import { useState } from "react";

interface WrappedSummary {
  month: number;
  year: number;
  totalVisits: number;
  totalMinutes: number;
  totalCalories: number;
  favoriteZones: { name: string; count: number }[];
}

// Dynamically import @react-pdf/renderer only when the user clicks export — it's
// a heavy dependency we don't want in the initial bundle.
export default function WrappedPdfButton({ report, userEmail }: { report: WrappedSummary; userEmail?: string }) {
  const [busy, setBusy] = useState(false);

  async function downloadPdf() {
    setBusy(true);
    try {
      const pdf = await import("@react-pdf/renderer");
      const { Document, Page, Text, View, StyleSheet, pdf: makePdf } = pdf;

      const styles = StyleSheet.create({
        page:    { padding: 36, fontFamily: "Helvetica", color: "#0f172a" },
        header:  { fontSize: 24, fontWeight: 700, marginBottom: 4, color: "#10b981" },
        sub:     { fontSize: 11, color: "#64748b", marginBottom: 16 },
        h2:      { fontSize: 14, fontWeight: 700, marginTop: 16, marginBottom: 6, color: "#0f172a" },
        statRow: { flexDirection: "row", gap: 12, marginTop: 6, marginBottom: 6 },
        stat:    { flex: 1, padding: 10, backgroundColor: "#f1f5f9", borderRadius: 6 },
        label:   { fontSize: 9, color: "#64748b", textTransform: "uppercase", letterSpacing: 1 },
        value:   { fontSize: 18, marginTop: 2, color: "#0f172a", fontWeight: 700 },
        listItem:{ fontSize: 11, marginBottom: 3, color: "#1e293b" },
        footer:  { position: "absolute", bottom: 24, left: 36, right: 36, fontSize: 9, color: "#94a3b8", textAlign: "center" },
      });

      const doc = (
        <Document>
          <Page size="A4" style={styles.page}>
            <Text style={styles.header}>FitFlow Wrapped</Text>
            <Text style={styles.sub}>
              {userEmail ?? "Member"} • {String(report.month).padStart(2, "0")}/{report.year}
            </Text>

            <Text style={styles.h2}>The numbers</Text>
            <View style={styles.statRow}>
              <View style={styles.stat}>
                <Text style={styles.label}>Sessions</Text>
                <Text style={styles.value}>{report.totalVisits}</Text>
              </View>
              <View style={styles.stat}>
                <Text style={styles.label}>Minutes</Text>
                <Text style={styles.value}>{report.totalMinutes}</Text>
              </View>
              <View style={styles.stat}>
                <Text style={styles.label}>Calories (est.)</Text>
                <Text style={styles.value}>{report.totalCalories}</Text>
              </View>
            </View>

            <Text style={styles.h2}>Favorite zones</Text>
            {report.favoriteZones.length === 0 ? (
              <Text style={styles.listItem}>No zones recorded this month.</Text>
            ) : (
              report.favoriteZones.slice(0, 5).map((z) => (
                <Text style={styles.listItem} key={z.name}>• {z.name} — {z.count} visit{z.count === 1 ? "" : "s"}</Text>
              ))
            )}

            <Text style={styles.footer}>
              Generated by FitFlow OS • {new Date().toLocaleDateString()}
            </Text>
          </Page>
        </Document>
      );

      const blob = await makePdf(doc).toBlob();
      const url  = URL.createObjectURL(blob);
      const a    = document.createElement("a");
      a.href     = url;
      a.download = `fitflow-wrapped-${report.year}-${String(report.month).padStart(2, "0")}.pdf`;
      a.click();
      setTimeout(() => URL.revokeObjectURL(url), 5000);
    } catch (e: any) {
      alert(`PDF export failed: ${e.message ?? e}`);
    } finally {
      setBusy(false);
    }
  }

  return (
    <button
      onClick={downloadPdf}
      disabled={busy}
      className="rounded-full bg-emerald-500/90 px-4 py-1 text-xs font-semibold text-slate-900 hover:bg-emerald-400 disabled:opacity-50"
    >
      {busy ? "Generating PDF…" : "Download PDF"}
    </button>
  );
}
